/run/initialize

/vis/open OGL
/vis/drawVolume
/vis/viewer/set/autoRefresh true

/vis/scene/add/trajectories rich smooth

# Draw only optical photons created by the Cerenkov process.
/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add opticalphoton
/vis/filtering/trajectories/create/attributeFilter
/vis/filtering/trajectories/attributeFilter-0/setAttribute CPN
/vis/filtering/trajectories/attributeFilter-0/addValue Cerenkov
/vis/filtering/trajectories/mode hard

/vis/scene/endOfEventAction refresh

# /run/beamOn 1